server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/application_launcher
    username: user
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml