version: '3.9'

services:
  postgres-database:
    image: postgres:14
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application_launcher
    ports:
      - "5432:5432"
